- object-store-service/src/main/java/collaboratory/storage/object/store/config/S3Config.java
- object-store-service/src/main/resources/application.yml
expose S3 connection parameters
> Expose configuration for S3 Connection

- object-store-service/src/main/java/collaboratory/storage/object/store/controller/ObjectDownloadController.java
- object-store-service/src/main/java/collaboratory/storage/object/store/controller/ObjectUploadController.java
- object-store-service/src/main/java/collaboratory/storage/object/store/service/upload/ObjectUploadService.java
cleaned up some message wording
> COL-41.1 - fix missing access token in audit log message

- object-store-service/src/main/java/collaboratory/storage/object/store/config/SecurityConfig.java
- object-store-service/src/main/java/collaboratory/storage/object/store/controller/ObjectDownloadController.java
- object-store-service/src/main/java/collaboratory/storage/object/store/controller/ObjectUploadController.java
- object-store-service/src/main/java/collaboratory/storage/object/store/util/TokenHasher.java
- object-store-service/src/main/resources/application.yml
Used Guava com.google.common.hash.Hashing implementation of MD5
> add MD5 hashing to tokens that are being audit-logged

- object-store-service/src/main/conf/wrapper.conf
- object-store-service/src/main/resources/application.yml
profile:include does not do what you think it does
> back out 'import' changes in profile configuration

- object-store-service/src/main/scripts/crontab
- object-store-service/src/main/scripts/harvest.py
- object-store-service/src/main/scripts/harvest.sh
SCRUBBED AWS CREDENTIALS FROM SHELL SCRIPT
included sample crontab entry
> add script files to upload log and audit log files to S3

- README.md
- dcc-storage-client/pom.xml
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/DownloadCommand.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/MountCommand.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/UploadCommand.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/download/DownloadService.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/progress/Progress.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/util/ProfileRepoValidator.java
- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/ServerMain.java
- pom.xml
add manifest validation logic: ensure repo_code value consistent with specified client profile
> COL-310 Repo_code validation

- dcc-storage-client/pom.xml
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/config/ClientConfig.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/transport/StorageService.java
- dcc-storage-server/pom.xml
- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/controller/BenchmarkObjectUploadController.java
- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/controller/ObjectDownloadController.java
- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/controller/ObjectUploadController.java
Storage service logs User-Agent received into audit log
> added User-Agent header to default request headers

- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/ViewCommand.java
> specify correct Object Id Validator on parameters

- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/cli/CreatableDirectoryValidator.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/cli/DirectoryValidator.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/DownloadCommand.java
- dcc-storage-client/src/main/java/org/icgc/dcc/storage/client/command/ViewCommand.java
- dcc-storage-client/src/test/java/org/icgc/dcc/storage/client/ClientMainTest.java
...instead of aborting with error
> create specified output directory if it doesn't exist

- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/repository/s3/S3UploadService.java
- dcc-storage-server/src/main/java/org/icgc/dcc/storage/server/repository/s3/S3UploadStateStore.java
- icgc-storage-client/src/main/conf/application.properties
Fixes:
1. Catch 404 errors for CompleteMultiPartUpload request
2. Post completion of MultiPart upload; check if part is available before deleting each part
> Fix for large file upload timeout issue

- score-server/pom.xml
> score-101-update-pom

- score-client/src/main/java/bio/overture/score/client/command/ViewCommand.java
- score-client/src/main/java/bio/overture/score/client/slicing/SamFileBuilder.java
- score-client/src/main/java/bio/overture/score/client/upload/UploadStateStore.java
- score-client/src/main/java/bio/overture/score/client/view/Viewer.java
> Score 137 view command bugfix

- Dockerfile.server
- Makefile
- README.md
- docker-compose.yml
- hooks/build
- hooks/push
Simplified docker build to use the source code from the current directory and just build that
> score docker build from source

- score-client/Dockerfile
- score-client/src/main/bin/score-client
> Fix broken Oracle java build

- Makefile
- docker-compose.yml
- docker/ego-init/init.sql
- docker/score-client-init/publish-analysis.sh
- docker/score-client-init/run_tests.sh
- docker/score-client-init/test-abc.manifest
- docker/score-client-init/test-ca.manifest
- docker/score-client-init/test_manifests.sh
- docker/score-client-init/unpublish-analysis.sh
- docker/tools/score-client-demo
- docker/tools/score-client-dev
- fixed version of song-server and ego-api
- fixed corruped ego-postgres init
- cleaned up Makefile
- modified scripts slightly
> fixed-up-small-issues

- Jenkinsfile
Test deployment to artifactory!
> Define release process for artifactory roadmap#148

- .gitignore
- Jenkinsfile
- README.md
Reverts overture-stack/score#195
> Revert "Define release process for artifactory roadmap#148"

- pom.xml
- score-client/pom.xml
- score-client/src/main/conf/application.properties
- score-client/src/main/java/bio/overture/score/client/command/AbstractClientCommand.java
- score-client/src/main/resources/application.yml
- score-core/pom.xml
- score-fs/pom.xml
- score-server/pom.xml
- score-test/pom.xml
Added
```
accessToken=mytoken
metadata.url=https://example.song.org
```
to the properties file. Ran the following commands and they all output as expected:
1. **./bin/score-client info**
```
> SCORE Client
Active Configuration: 
Profile:          default
Storage URL: https://virginia.cloud.icgc.org
Metadata URL:https://example.song.org
Access Token:     mytoken
```
2. **./bin/score-client --profile collab info**
```
> SCORE Client
Active Configuration: 
Profile:          collab
Storage URL: https://storage.cancercollaboratory.org
Metadata URL:https://song.cancercollaboratory.org
Access Token:     mytoken
```
3. **./bin/score-client --profile aws info**
```
> SCORE Client
Active Configuration: 
Profile:          aws
Storage URL: https://virginia.cloud.icgc.org
Metadata …
```
> Fix default configs

- Dockerfile
Build and test with
```
docker build --target client ./ -t myimage
docker run --rm -it myimage  bin/score-client help
```
> fixed broken client

- score-server/src/main/java/bio/overture/score/server/config/SecurityConfig.java
- score-server/src/main/java/bio/overture/score/server/properties/ScopeProperties.java
- score-server/src/main/java/bio/overture/score/server/security/scope/AbstractScopeAuthorizationStrategy.java
- score-server/src/main/java/bio/overture/score/server/security/scope/DownloadScopeAuthorizationStrategy.java
- score-server/src/main/java/bio/overture/score/server/security/scope/UploadScopeAuthorizationStrategy.java
- score-server/src/main/resources/application.yml
- score-server/src/test/java/bio/overture/score/server/security/DownloadScopeAuthorizationStrategyTest.java
- score-server/src/test/java/bio/overture/score/server/security/UploadScopeAuthorizationStrategyTest.java
> Score 257 multiple system scopes

- pom.xml
- score-client/pom.xml
- score-core/pom.xml
- score-fs/pom.xml
- score-server/pom.xml
- score-server/src/main/java/bio/overture/score/server/config/SecurityConfig.java
- score-server/src/main/java/bio/overture/score/server/properties/ScopeProperties.java
- score-server/src/main/java/bio/overture/score/server/security/scope/AbstractScopeAuthorizationStrategy.java
- score-server/src/main/java/bio/overture/score/server/security/scope/DownloadScopeAuthorizationStrategy.java
- score-server/src/main/java/bio/overture/score/server/security/scope/UploadScopeAuthorizationStrategy.java
- score-server/src/main/resources/application.yml
- score-server/src/test/java/bio/overture/score/server/security/DownloadScopeAuthorizationStrategyTest.java
- score-server/src/test/java/bio/overture/score/server/security/UploadScopeAuthorizationStrategyTest.java
- score-test/pom.xml
> Release Candidate 5.0.0

- Jenkinsfile
- Jenkinsfile - publish docker image to ghcr.io registry for develop and master branch builds
- Jenkinsfile - pipeline build/publish steps variables revisited
> Add publish to ghcr

- Jenkinsfile
- Jenkinsfile - fixed `docker push` instructions to use correct image version
> Jenkinsfile - fixed docker push instructions to use correct image version

- score-client/src/main/java/bio/overture/score/client/upload/UploadStateStore.java
- score-client/src/main/java/bio/overture/score/client/upload/s3/S3UploadService.java
- score-client/src/main/resources/application.yml
- score-client/src/test/java/bio/overture/score/client/upload/UploadStateStoreTests.java
related issues: https://github.com/overture-stack/score/issues/302
changes:
- add config for upload state dir
- tests updates
> make upload state parent directory configurable

- Jenkinsfile
Reverts overture-stack/score#354 jenkins file timeout change
> Revert "Jenkins timeout change"

- score-client/src/main/java/bio/overture/score/client/metadata/legacy/LegacyMetadataService.java
Adding checks for .crai files.
> View showing header only - #229

- Jenkinsfile
> increase Jenkins timeout

- Jenkinsfile
Use the right Jenkins job to deploy artifacts with Helm
> update DeployWithHelm job name in Jenkinsfile
