object-store-client/src/main/java/collaboratory/storage/object/store/client/cli/command/UploadCommand.java
object-store-client/src/main/java/collaboratory/storage/object/store/client/transport/ObjectStoreServiceProxy.java
object-store-client/src/main/java/collaboratory/storage/object/store/client/upload/ObjectUpload.java
object-store-service/src/main/java/collaboratory/storage/object/store/controller/BenchmarkObjectUploadController.java
object-store-service/src/main/java/collaboratory/storage/object/store/controller/ObjectUploadController.java
object-store-service/src/main/java/collaboratory/storage/object/store/service/upload/ObjectUploadService.java

changed request parameter name from 'overwritten' to 'overwrite' - this is why there is a service-side change

fix -force overwrite option

---

pom.xml
score-client/src/main/java/bio/overture/score/client/command/MountCommand.java
score-client/src/main/java/bio/overture/score/client/mount/MountStorageContext.java

This fixes a potential 404 that can occur when there are unregistered objects in the object storage.
This also ensures no mounting of unregistered objects is attempted.
Also an issue with FUSE was discovered, we can no longer mount all of collaboratory to a single directory as the number of files appears too large for FUSE to handle.

do permission check against registered entity, not random object id

---

score-server/src/main/java/bio/overture/score/server/controller/DownloadController.java
score-server/src/main/java/bio/overture/score/server/repository/DownloadService.java
score-server/src/main/java/bio/overture/score/server/repository/azure/AzureDownloadService.java
score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java
score-server/src/test/java/bio/overture/score/server/repository/s3/S3DownloadServiceTest.java
score-server/src/test/java/bio/overture/score/server/service/download/ObjectDownloadServiceTest.java

When song tries to publish, it calls the download endpoint on score. Since the analysis is currently
UNPUBLISHED and score will only allow downloads for PUBLISHED files, therefore song cannot publish
because score only allows published files to be download. Fix was to add a new path param, that will
return object spec WITHOUT urls.
Test was not included, as it required stubbing out the entire universe.
related to #140

fix: Deadlock fix with song and score

---

docker-compose.yml
score-server/src/main/java/bio/overture/score/server/config/SecurityConfig.java
score-server/src/main/resources/application.yml

ran the integration test using /o/check_api_key with tokenname==apiKey, with the following command:
`make clean test-upload-and-download DEMO_MODE=1`

Added configurable token name to support  /o/check_api_key for ego

---

Dockerfile
Dockerfile.dev

by default, container is started with `root` user, however it can be started with `score` user by adding  ` u score` to the docker run command, and will allow access to mounted directories

updated security for client docker

---

README.md

Removed reference to circle CI in the README file. 
We need to remove the other references to circle CI from Github and/or the circle CI website.

Change: Removed CircleCI from README

---

score-client/src/main/java/bio/overture/score/client/metadata/legacy/LegacyMetadataClient.java

changes:
- use serviceTemplate (which is the restTemplate being used to talk to score with oauth configs) to make request to `/entities` endpoints instead of directly using objectMapper
this change doesn't affect current song-score client operations, and is being made to support: https://github.com/overture-stack/score/issues/279

Auth to metadata

---

score-client/src/main/java/bio/overture/score/client/metadata/legacy/LegacyMetadataClient.java

issue: https://github.com/overture-stack/score/issues/280
changes:
- use entities endpoint functions to get objectIds. This change is building on the restTemplate change from previous metadataclient changes so oauth will be passed to song/metadata server.

use legacy entities endpoint to get objectids

---

pom.xml
score-client/pom.xml
score-client/src/main/java/bio/overture/score/client/upload/azure/AzureUploadService.java
score-core/pom.xml
score-fs/pom.xml
score-server/pom.xml
score-test/pom.xml

- Upload Block Size configurable for Azure; Sensible default included
- ICGC DCC Song and Score URL config for Azure profile

Release Candidate 5.8.1

---

Dockerfile
Dockerfile.dev
score-client/src/main/java/bio/overture/score/client/command/DownloadCommand.java

Changes for score-client JDK update from 11 to 17, changing analysisId to analysis-id and studyId to study-id for the parameters-validation error message to avoid confusion. Ticket - https://github.com/overture-stack/score/issues/333

Score-client JDK update from 11 to 17

---

Jenkinsfile

Increasing the timeout for jenkins build to 60 minutes from 30 minutes as https://github.com/overture-stack/score/commit/09cb8e43b13e9d6737198c33f20baaf859119c8d was failing due to a timeout.

Jenkins timeout change

---

pom.xml

Set a list of Remove Maven repositories in pom.xml

add Maven repositories

---

Jenkinsfile
score-client/pom.xml

Upgraded from htsjdk 2.1.0 to 2.16.0 to support compressed zip files.

Allow `--reference-file` to use compressed BGZIP files#347

---

Dockerfile

Fix docker image used to compile project using JDK 11

using JDK image as builder

---

Jenkinsfile

Upgrade from docker image **docker:18.06-dind** to **docker:20.10-dind** (docker v20.10.24).
This upgrade is required to build and image based on ubuntu 22.04

update docker dind

---

Jenkinsfile

This Docker dind version now requires to configure TLS env variables.
Ref: [link](https://hub.docker.com/_/docker#TLS:~:text=use%20this%20image-,TLS,-Starting%20in%2018.09)

fix docker dind TLS

---

score-server/src/main/java/bio/overture/score/server/repository/azure/AzureDownloadService.java

this fix addresses the issue where some blobs from Azure miss the value for contentMd5 property which breaks the download.

fix for issue #385

---

score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java
score-server/src/test/java/bio/overture/score/server/service/download/ObjectDownloadServiceTest.java

This commit refactors the **S3DownloadService** to utilize the S3 API directly instead of relying on a separate .meta file for object information. 
These changes improve the resilience of the S3 download service by-
- Preventing unexpected service failures due to null values or missing .meta files.
- Ensuring consistent execution flow by handling different scenarios uniformly.
- Null Handling: The code now checks if objectSpec is null and handles the case, preventing potential issues encountered earlier. 
- The code is responsible for using the part size (length) from the S3 API. By fetching object metadata and using it to fill part URLs and create the **ObjectSpecification**, the code ensures that the sizes and offsets match the actual stored parts on S3, rather than solely relying on …

S3 Service using API instead of .meta file

---

score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java

The code has been refactored to use a different method for retrieving the S3 bucket name. Previously, the method **getStateBucketName** was used to obtain the bucket name, but it has been replaced with **getObjectBucketName**. This change ensures that the correct bucket name is used when fetching the object metadata from the S3 client

Refactor S3 Bucket Name Retrieval Method

---

score-core/src/main/java/bio/overture/score/core/model/ObjectKey.java
score-core/src/main/java/bio/overture/score/core/util/ObjectKeys.java
score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java
score-server/src/main/java/bio/overture/score/server/repository/s3/S3ListingService.java

All three code changes introduced the use of the **isBlank()** method to handle empty strings in different contexts:
**getKey and getMetaKey methods**: These methods now check if the dir variable is empty. If it is empty, they return only the objectId. Otherwise, they maintain the original behavior of concatenating the directory path and object identifier. This provides more flexibility in handling scenarios where the data might not have a specific directory structure.
**getObjectMetaKey method**: Similar to the previous change, this method now checks if the dataDir parameter is empty. If it's empty, it creates a key using only the objectId with the ".meta" extension. This allows the method to function even when no directory path is provided.
**readBucket method:** This method now checks …

Improve String Handling for Empty and Whitespace Parameters in Key and Bucket Methods

---

score-core/src/main/java/bio/overture/score/core/model/Part.java
score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java

When objectSpec is null, we retrieve objectMetadata to create a new objectSpec. This process involves calculating a list of parts using the divide method, which takes offset and length as inputs. If forExternalUse is false and length is 0, we utilize meta.getContentLength() to get the metadata length, which helps in generating the list of parts for creating the objectSpec

Generate Logical Parts for object downloads when no .meta file is available

---

score-server/src/main/java/bio/overture/score/server/config/S3Config.java
score-server/src/main/java/bio/overture/score/server/repository/s3/S3DownloadService.java
score-server/src/main/resources/application.yml

For S3 downloads, when handling downloads in cases where the `.meta` file is not found, we need to retrieve the MD5 sum from the Object metadata. Our current implementation of this is reading the value of the eTag, but this is not guaranteed to contain an MD5 hash (and for multipart uploads is known to never contain the MD5 hash).
This change introduces a function to get the MD5 hash from the metadata. The function has two cases to check for where the MD5 hash might be.
1. Priority is to use the built in S3 getContentMD5() method. If the hash is found here then this will be returned. 
2. Allow reading of a custom (user defined) metadata property. This allows a system administrator to assign the Base64 encoded MD5 hash in a custom location. This is given the default property name …

Retrieve MD5 from object metadata
